{{- if .Values.api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: {{ .Values.api.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/part-of: vertrouwd-bouwen
    spec:
      containers:
        - name: api
          image: {{ .Values.steiger.api.image }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.container.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env | quote }}
            - name: HOSTNAME
              value: {{ .Values.api.container.hostname | quote }}
            - name: PORT
              value: {{ .Values.api.container.port | quote }}
            {{- if .Values.api.env.jwtSecret }}
            - name: JWT_SECRET
              {{- if .Values.api.env.jwtSecret.valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.env.jwtSecret.valueFrom.secretKeyRef.name }}
                  key: {{ .Values.api.env.jwtSecret.valueFrom.secretKeyRef.key }}
              {{- else if .Values.api.env.jwtSecret.value }}
              value: {{ .Values.api.env.jwtSecret.value | quote }}
              {{- end }}
            {{- end }}
            - name: CORS_ORIGIN
              value: {{ .Values.api.env.corsOrigin | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.env.databaseUrl.valueFrom.secretKeyRef.name }}
                  key: {{ .Values.api.env.databaseUrl.valueFrom.secretKeyRef.key }}
          {{- if .Values.api.resources }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: api
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: http
{{- end }}
