---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  replicas: {{ .minReplicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: vertrouwd-bouwen
    spec:
      containers:
        - name: frontend
          image: {{ $.Values.steiger.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          # envFrom:
          # - secretRef:
          #     name: frontend-secrets
          env:
            - name: ENVIRONMENT
              value: {{ $.Values.env }}
            - name: HOSTNAME
              value: 0.0.0.0
            - name: PORT
              value: "3000"
            - name: API_BASE_URL
              value: http://api:80/api
      imagePullSecrets:
        - name: github-registry

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - port: 80
    targetPort: http

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  hostnames:
    - frontend.vertrouwd-bouwen.juliamertz.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: default
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: frontend
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: frontend
spec:
  hostnames:
    - frontend.vertrouwd-bouwen.juliamertz.dev
  targetCertificate:
    name: gateway-tls
    namespace: default
