{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: vertrouwd-bouwen
    spec:
      containers:
        - name: frontend
          image: {{ .Values.steiger.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.container.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env | quote }}
            - name: HOSTNAME
              value: {{ .Values.frontend.container.hostname | quote }}
            - name: PORT
              value: {{ .Values.frontend.container.port | quote }}
            - name: API_BASE_URL
              value: {{ .Values.frontend.env.apiBaseUrl | quote }}
          {{- if .Values.frontend.resources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http

{{- if .Values.frontend.ingress.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  hostnames:
    - {{ .Values.frontend.ingress.hostname }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.frontend.ingress.gateway.name }}
      namespace: {{ .Values.frontend.ingress.gateway.namespace }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: frontend
          port: {{ .Values.frontend.service.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

{{- if .Values.tls.enabled }}
---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: frontend
spec:
  hostnames:
    - {{ .Values.frontend.ingress.hostname }}
  targetCertificate:
    name: {{ .Values.frontend.ingress.certificate.name }}
    namespace: {{ .Values.frontend.ingress.certificate.namespace }}
{{- end }}
{{- end }}
{{- end }}
